const healthVals = [
  'Alcohol-free',
  'Celery-free',
  'Crustacean-free',
  'Dairy-free',
  'Egg-free',
  'Fish-free',
  'Gluten-free',
  'Kidney friendly',
  'Kosher',
  'Low potassium',
  'Lupine-free',
  'Mustard-free',
  'No oil added',
  'Low-sugar',
  'Paleo',
  'Peanut-free',
  'Pescatarian',
  'Pork-free',
  'Red meat-free',
  'Sesame-free',
  'Shellfish-free',
  'Soy-free',
  'Sugar-conscious',
  'Tree-nut-free',
  'Vegan',
  'Vegetarian',
  'Wheat-free'
];

export default healthVals
